import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // shadcn vendor code. Owned by the CLI, mirrored from .prettierignore, and
    // regenerated by `npx shadcn add` — so lint findings here are not actionable.
    "src/components/ui/**",
  ]),
]);

export default eslintConfig;
